# Generated by Django 3.0.1 on 2019-12-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='paid_until',
            field=models.DateField(auto_now_add=True),
        ),
    ]
