# Generated by Django 3.0.1 on 2019-12-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_content', '0002_auto_20191224_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='paid_until',
            field=models.DateField(),
        ),
    ]
