# Generated by Django 3.0.1 on 2019-12-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_content', '0007_auto_20191231_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.FilePathField(blank=True, max_length=256, null=True, path='media/'),
        ),
    ]
