# Generated by Django 3.0.1 on 2019-12-31 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_content', '0008_auto_20191231_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='associated_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member_content.Member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.FilePathField(blank=True, max_length=256, null=True, path='member_content/media/'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_line', models.CharField(max_length=256)),
                ('second_line', models.CharField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.IntegerField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longetude', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member_content.Member')),
            ],
        ),
    ]
