# Generated by Django 3.0.1 on 2019-12-31 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_content', '0010_auto_20191231_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member_content.Address'),
        ),
    ]
