# Generated by Django 3.0.1 on 2019-12-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20191224_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='second_line',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
