# Generated by Django 3.0.1 on 2019-12-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20191224_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Club name'),
        ),
        migrations.AlterField(
            model_name='club',
            name='text',
            field=models.TextField(verbose_name='Content'),
        ),
    ]
