# Generated by Django 3.0.1 on 2019-12-31 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_content', '0009_auto_20191231_1256'),
        ('clubs', '0004_auto_20191225_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member_content.Address'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
