# Generated by Django 3.0.1 on 2019-12-31 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('clubs', '0006_auto_20191231_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.Address'),
        ),
    ]
