# Generated by Django 3.0.1 on 2020-01-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20191231_1843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
