# Generated by Django 3.0.1 on 2019-12-27 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_caption', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('top_level_menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.ToplevelEntry')),
            ],
        ),
    ]
